Vagrant.configure("2") do |config|
    config.vm.box = "debian/trixie64"

    config.vm.synced_folder ".", "/vagrant", disabled: true
        
    config.vm.define "msallS" do |server|
        server.vm.hostname = "msallS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider :libvirt do |lv|
            lv.driver = "qemu"
            lv.cpu_mode = "custom"
            lv.cpu_model = "qemu64"
            lv.memeory = 2048
            lv.cpu = 2
        end
        server.vm.provision "file", source: "confs", destination: "/home/vagrant/confs"
        server.vm.provision "shell", path: "scripts/setup.sh"
    end
end